services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports: # expose port 3000 to the outside world, so that we can actually access it
      - 3000:3000
    env_file: # use the .env file to set environment variables
      - ./backend/.env

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: # use the .env file to set environment variables
      - ./frontend/.env  
    ports:
      - 5173:5173

  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data:/data/db